name: Deploy Supabase Changes

on:
  push:
    branches:
      - main
    paths:
      - 'supabase/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      PROJECT_ID: ivypwrrvehgguhzffyoj

    steps:
    - uses: actions/checkout@v2

    - name: Setup Supabase CLI
      uses: supabase/setup-cli@v1

    - name: Link to Supabase project
      run: supabase link --project-ref $PROJECT_ID

    - name: Push database changes
      run: supabase db push

    - name: Deploy Supabase functions
      run: supabase functions deploy

